# Generated by Django 3.2.13 on 2022-06-02 11:06

import datetime
from django.db import migrations, models
import t.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIncrementFields',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='wj_finish',
            fields=[
                ('id', models.CharField(max_length=128)),
                ('dpt_name', models.CharField(max_length=20, verbose_name='机构名称')),
                ('report_no', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='报案号')),
                ('report_date', models.DateTimeField(verbose_name='报案时间')),
                ('register_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('car_person', models.CharField(blank=True, max_length=80, null=True, verbose_name='car_person(在此为被回访人)')),
                ('injured_person', models.CharField(blank=True, max_length=80, null=True, verbose_name='injured_person(没有用到)')),
                ('estimate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='立案金额')),
                ('car_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='car_amount(没有用到)')),
                ('injured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='injured_amount(没有用到)')),
                ('visited', models.CharField(blank=True, max_length=30, null=True, verbose_name='visited(没有用到)')),
                ('visit_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='柜面电话')),
                ('wj_reason1', models.CharField(blank=True, choices=[('无人接听', '无人接听'), ('联系通畅', '联系通畅'), ('有历史记录', '有历史记录')], max_length=100, null=True, verbose_name='未决原因1')),
                ('wj_reason2', models.CharField(blank=True, max_length=100, null=True, verbose_name='未决原因2')),
                ('wj_reason3', models.CharField(blank=True, max_length=100, null=True, verbose_name='未决原因3(没有用到)')),
                ('is_coupon', models.CharField(blank=True, max_length=20, null=True, verbose_name='is_coupon(没有用到)')),
                ('remake', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('visited_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='被回访人电话')),
                ('visit_dpt', models.CharField(blank=True, max_length=20, null=True, verbose_name='柜面机构')),
                ('visit_dpt2', models.CharField(blank=True, max_length=20, null=True, verbose_name='柜面网点')),
                ('num_issued', models.CharField(blank=True, max_length=30, null=True, verbose_name='num_issued(没有用到)')),
                ('dpt_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='岗位')),
                ('is_pref', models.CharField(blank=True, max_length=20, null=True, verbose_name='is_pref(没有用到)')),
                ('counter_specify', models.CharField(blank=True, max_length=20, null=True, verbose_name='counter_specify(没有用到)')),
                ('event_type', models.CharField(max_length=20, verbose_name='案件类型')),
                ('complaint_risk', models.CharField(blank=True, max_length=30, null=True, verbose_name='投诉风险')),
                ('case_closed', models.CharField(blank=True, choices=[('0结案', '0结案'), ('不结案', '不结案'), ('有历史记录', '有历史记录')], max_length=10, null=True, verbose_name='结案类型')),
                ('sound_record', models.FileField(blank=True, null=True, upload_to=t.models.PathAndRename('t_sound_record/'), verbose_name='回访录音')),
                ('tracer', models.CharField(max_length=30, verbose_name='回访柜面')),
                ('tracering_date', models.DateTimeField(verbose_name='回访时间')),
                ('finish_time', models.DateTimeField(verbose_name='回访结束时间')),
            ],
            options={
                'verbose_name': '已完成任务',
                'verbose_name_plural': '已完成任务',
            },
        ),
        migrations.CreateModel(
            name='wj_unfinish',
            fields=[
                ('id', models.CharField(max_length=128)),
                ('dpt_name', models.CharField(max_length=20, verbose_name='机构名称')),
                ('report_no', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='报案号')),
                ('report_date', models.DateTimeField(verbose_name='报案时间')),
                ('register_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('car_person', models.CharField(blank=True, max_length=80, null=True, verbose_name='car_person(在此为被回访人)')),
                ('injured_person', models.CharField(blank=True, max_length=80, null=True, verbose_name='injured_person(没有用到)')),
                ('estimate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='立案金额')),
                ('car_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='car_amount(没有用到)')),
                ('injured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='injured_amount(没有用到)')),
                ('visited', models.CharField(blank=True, max_length=30, null=True, verbose_name='visited(没有用到)')),
                ('tracer', models.CharField(blank=True, max_length=30, null=True, verbose_name='回访柜面')),
                ('tracering_date', models.DateTimeField(blank=True, null=True, verbose_name='回访时间')),
                ('visit_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='柜面电话')),
                ('wj_reason1', models.CharField(blank=True, choices=[('无人接听', '无人接听'), ('联系通畅', '联系通畅'), ('有历史记录', '有历史记录')], max_length=100, null=True, verbose_name='未决原因1')),
                ('wj_reason2', models.CharField(blank=True, max_length=100, null=True, verbose_name='未决原因2')),
                ('wj_reason3', models.CharField(blank=True, max_length=100, null=True, verbose_name='未决原因3(没有用到)')),
                ('is_coupon', models.CharField(blank=True, max_length=20, null=True, verbose_name='is_coupon(没有用到)')),
                ('remake', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='回访结束时间')),
                ('visited_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='被回访人电话')),
                ('visit_dpt', models.CharField(blank=True, max_length=20, null=True, verbose_name='柜面机构')),
                ('visit_dpt2', models.CharField(blank=True, max_length=20, null=True, verbose_name='柜面网点')),
                ('num_issued', models.CharField(blank=True, max_length=30, null=True, verbose_name='num_issued(没有用到)')),
                ('dpt_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='岗位')),
                ('is_pref', models.CharField(blank=True, max_length=20, null=True, verbose_name='is_pref(没有用到)')),
                ('counter_specify', models.CharField(blank=True, max_length=20, null=True, verbose_name='counter_specify(没有用到)')),
                ('event_type', models.CharField(max_length=20, verbose_name='案件类型')),
                ('complaint_risk', models.CharField(blank=True, max_length=30, null=True, verbose_name='投诉风险')),
                ('case_closed', models.CharField(blank=True, choices=[('0结案', '0结案'), ('不结案', '不结案'), ('有历史记录', '有历史记录')], max_length=10, null=True, verbose_name='结案类型')),
                ('sound_record', models.FileField(blank=True, null=True, upload_to=t.models.PathAndRename('t_sound_record/'), verbose_name='回访录音')),
            ],
            options={
                'verbose_name': '未完成任务',
                'verbose_name_plural': '未完成任务',
            },
        ),
    ]
